// Generated by Assets/site_to_swift.py from Assets/work/site-plan.json. Do not edit by hand.

import Foundation

enum WorldSiteData {
    static let gridUnit: Float = 3
    static let groundColor = "Unchanged: the 160 m base plane (0.36,0.36,0.37) at y -0.14 and WorldYard's 44x34 slab (0.37,0.37,0.38) at y -0.135 (x -24..20, z -18.5..15.5), which now lies under the lot, both aprons and the near halves of both streets; tiles sit on it at y -0.12 (WorldSite places roads at y+0.01), so the kerb tops and the 1.5 m footpaths are at +0.03 and the road asphalt at -0.12. Road tiles skip the grey wash and keep the kit's own asphalt (dark) and concreteSmooth (light) greys, which is what makes the kerb line read. Grid: 3 m tiles; x edges at 10.5+3k, z edges at 9.5+3k, the same grid as the facade tiles and the fence panels."
    static let roads: [WorldSite.Piece] = [
        .init("asphalt_side", -24, 11, yaw: 180, scale: 1),   // FRONT STREET runs along x. Near kerb row z 9.5-12.5: pavement (raised 0.15) on z 9.5-11 = the lot's 1.5 m footpath, kerb face at z 11, asphalt z 11-12.5. yaw 180 puts the tile's local +z pavement half toward -z (the lot).
        .init("asphalt_side", -21, 11, yaw: 180, scale: 1),   // near kerb
        .init("asphalt_side", -18, 11, yaw: 180, scale: 1),   // near kerb
        .init("asphalt_side", -15, 11, yaw: 180, scale: 1),   // near kerb, in front of the wing's south face (which stands 2.5 m behind the footpath at z 7)
        .init("asphalt_center", -12, 11, yaw: 0, scale: 1),   // COMPOUND GATE CROSSOVER x -13.5..-7.5: kerb dropped, flat asphalt from the road to the gate (gate x -13.5..-8.5)
        .init("asphalt_center", -9, 11, yaw: 0, scale: 1),   // compound gate crossover, second tile
        .init("asphalt_side", -6, 11, yaw: 180, scale: 1),   // near kerb resumes at x -7.5; the compound's short fence and the den's SW corner are 2.25 m behind it
        .init("asphalt_side", -3, 11, yaw: 180, scale: 1),   // near kerb in front of the den's +z side; the footpath back (z 9.5) is 2.25 m off the plinth (z 7.25)
        .init("asphalt_side", 0, 11, yaw: 180, scale: 1),   // near kerb
        .init("asphalt_side", 3, 11, yaw: 180, scale: 1),   // near kerb; drain grate and the moved cone on the asphalt against this kerb
        .init("asphalt_side", 6, 11, yaw: 180, scale: 1),   // near kerb
        .init("asphalt_side", 9, 11, yaw: 180, scale: 1),   // last near-kerb tile before the T; its kerb ends at (10.5,11) where the corner arc starts
        .init("asphalt_corner_outer", 12, 11, yaw: 180, scale: 1),   // T CORNER, lot side: the tile's quarter-disc of pavement (r 1.5, local +x+z) turned to -x-z, centred on the tile corner (10.5,9.5); arc ends meet the kerb lines at (10.5,11) and (12,9.5)
        .init("asphalt_center", 15, 11, yaw: 0, scale: 1),   // T mouth: the side street's carriageway (x 12-18) runs into the front street's (z 11-17)
        .init("asphalt_corner_outer", 18, 11, yaw: 90, scale: 1),   // T CORNER, far side: pavement quarter-disc turned to +x-z, centred on (19.5,9.5); arc ends meet the kerb lines at (18,9.5) and (19.5,11); street-name sign and hydrant stand on it
        .init("asphalt_side", 21, 11, yaw: 180, scale: 1),   // near kerb continues east of the T
        .init("asphalt_side", 24, 11, yaw: 180, scale: 1),   // near kerb, east end (x 25.5); beyond the frame at every zoom and orbit
        .init("asphalt_center", -24, 14, yaw: 0, scale: 1),   // CENTRE ROW z 12.5-15.5; carriageway is z 11-17, 6 m kerb to kerb, no centre line (back street)
        .init("asphalt_center", -21, 14, yaw: 0, scale: 1),   // centre
        .init("asphalt_center", -18, 14, yaw: 0, scale: 1),   // centre
        .init("asphalt_center", -15, 14, yaw: 0, scale: 1),   // centre
        .init("asphalt_center", -12, 14, yaw: 0, scale: 1),   // centre
        .init("asphalt_center", -9, 14, yaw: 0, scale: 1),   // centre
        .init("asphalt_center", -6, 14, yaw: 0, scale: 1),   // centre
        .init("asphalt_center", -3, 14, yaw: 0, scale: 1),   // centre
        .init("asphalt_center", 0, 14, yaw: 0, scale: 1),   // centre; manhole primitive at (1.5,14)
        .init("asphalt_center", 3, 14, yaw: 0, scale: 1),   // centre
        .init("asphalt_center", 6, 14, yaw: 0, scale: 1),   // centre
        .init("asphalt_center", 9, 14, yaw: 0, scale: 1),   // centre
        .init("asphalt_center", 12, 14, yaw: 0, scale: 1),   // centre, under the T
        .init("asphalt_center", 15, 14, yaw: 0, scale: 1),   // centre, under the T
        .init("asphalt_center", 18, 14, yaw: 0, scale: 1),   // centre, under the T
        .init("asphalt_center", 21, 14, yaw: 0, scale: 1),   // centre
        .init("asphalt_center", 24, 14, yaw: 0, scale: 1),   // centre
        .init("asphalt_side", -24, 17, yaw: 0, scale: 1),   // FAR KERB ROW z 15.5-18.5: asphalt z 15.5-17, kerb face z 17, pavement z 17-18.5 (yaw 0 = local +z pavement toward +z). Columns, poles, bench and flag stand on or just behind this footpath.
        .init("asphalt_side", -21, 17, yaw: 0, scale: 1),   // far kerb
        .init("asphalt_side", -18, 17, yaw: 0, scale: 1),   // far kerb
        .init("asphalt_side", -15, 17, yaw: 0, scale: 1),   // far kerb; unlit column at x -15 behind it
        .init("asphalt_side", -12, 17, yaw: 0, scale: 1),   // far kerb, in front of Unit A
        .init("asphalt_side", -9, 17, yaw: 0, scale: 1),   // far kerb, in front of Unit A
        .init("asphalt_side", -6, 17, yaw: 0, scale: 1),   // far kerb
        .init("asphalt_center", -3, 17, yaw: 0, scale: 1),   // UNIT A CROSSOVER x -4.5..-1.5: flat, into the forecourt on Unit A's +x side
        .init("asphalt_side", 0, 17, yaw: 0, scale: 1),   // far kerb; the bus-stop bench sits on this tile's pavement
        .init("asphalt_side", 3, 17, yaw: 0, scale: 1),   // far kerb; bus flag on its pavement
        .init("asphalt_center", 6, 17, yaw: 0, scale: 1),   // VACANT LOT'S OLD CROSSOVER x 4.5..7.5: flat; two jersey barriers block it at z 19.4
        .init("asphalt_side", 9, 17, yaw: 0, scale: 1),   // far kerb; the lit column at x 9 behind it
        .init("asphalt_side", 12, 17, yaw: 0, scale: 1),   // far kerb runs straight across the T (a T-junction, not a crossroads)
        .init("asphalt_side", 15, 17, yaw: 0, scale: 1),   // far kerb across the T
        .init("asphalt_side", 18, 17, yaw: 0, scale: 1),   // far kerb across the T
        .init("asphalt_side", 21, 17, yaw: 0, scale: 1),   // far kerb
        .init("asphalt_side", 24, 17, yaw: 0, scale: 1),   // far kerb, east end
        .init("asphalt_side", 12, 8, yaw: -90, scale: 1),   // SIDE STREET runs along z. Near kerb column x 10.5-13.5: pavement x 10.5-12 = the lot's footpath (yaw -90 turns the local +z pavement half to -x), kerb face x 12, asphalt x 12-13.5. Its kerb ends at (12,9.5) at the corner arc.
        .init("asphalt_center", 15, 8, yaw: 0, scale: 1),   // side street centre column x 13.5-16.5; carriageway x 12-18 (6 m)
        .init("asphalt_side", 18, 8, yaw: 90, scale: 1),   // far kerb column x 16.5-19.5: asphalt x 16.5-18, kerb face x 18, pavement x 18-19.5 (yaw 90 turns the pavement half to +x); kerb ends at (18,9.5) at the far corner arc
        .init("asphalt_side", 12, 5, yaw: -90, scale: 1),   // near kerb, along the den's east apron (plinth edge x 8.25, footpath back x 10.5); drain grate against it at z 5.2
        .init("asphalt_center", 15, 5, yaw: 0, scale: 1),   // centre
        .init("asphalt_side", 18, 5, yaw: 90, scale: 1),   // far kerb; the lit column at z 6 behind it
        .init("asphalt_side", 12, 2, yaw: -90, scale: 1),   // near kerb
        .init("asphalt_center", 15, 2, yaw: 0, scale: 1),   // centre
        .init("asphalt_side", 18, 2, yaw: 90, scale: 1),   // far kerb
        .init("asphalt_side", 12, -1, yaw: -90, scale: 1),   // near kerb
        .init("asphalt_center", 15, -1, yaw: 0, scale: 1),   // centre; manhole primitive at (15,-2)
        .init("asphalt_side", 18, -1, yaw: 90, scale: 1),   // far kerb
        .init("asphalt_side", 12, -4, yaw: -90, scale: 1),   // near kerb, level with the den's back wall (z -5); the lot's return fence meets the boundary at z -5.6
        .init("asphalt_center", 15, -4, yaw: 0, scale: 1),   // centre
        .init("asphalt_side", 18, -4, yaw: 90, scale: 1),   // far kerb; the low unit's roller door faces this stretch
        .init("asphalt_side", 12, -7, yaw: -90, scale: 1),   // near kerb; its kerb ends at z -8.5 where the lot gate crossover starts
        .init("asphalt_center", 15, -7, yaw: 0, scale: 1),   // centre
        .init("asphalt_side", 18, -7, yaw: 90, scale: 1),   // far kerb; the lit column at z -6 behind it
        .init("asphalt_center", 12, -10, yaw: 0, scale: 1),   // LOT GATE CROSSOVER z -14.5..-8.5: kerb dropped, flat from the road through the 6 m gate into the lorry lane
        .init("asphalt_center", 15, -10, yaw: 0, scale: 1),   // centre
        .init("asphalt_side", 18, -10, yaw: 90, scale: 1),   // far kerb; neighbour's dumpster on the apron behind it
        .init("asphalt_center", 12, -13, yaw: 0, scale: 1),   // lot gate crossover, second tile
        .init("asphalt_center", 15, -13, yaw: 0, scale: 1),   // centre
        .init("asphalt_side", 18, -13, yaw: 90, scale: 1),   // far kerb
        .init("asphalt_side", 12, -16, yaw: -90, scale: 1),   // near kerb resumes at z -14.5, beside the warehouse's east end (facade ends at x 10.5, z -17)
        .init("asphalt_center", 15, -16, yaw: 0, scale: 1),   // centre
        .init("asphalt_side", 18, -16, yaw: 90, scale: 1),   // far kerb
        .init("asphalt_side", 12, -19, yaw: -90, scale: 1),   // near kerb, along the warehouse's blank east wall
        .init("asphalt_center", 15, -19, yaw: 0, scale: 1),   // centre
        .init("asphalt_side", 18, -19, yaw: 90, scale: 1),   // far kerb
        .init("asphalt_side", 12, -22, yaw: -90, scale: 1),   // near kerb, north end (z -23.5); the road runs on toward unit_k on the base ground
        .init("asphalt_center", 15, -22, yaw: 0, scale: 1),   // centre, north end
        .init("asphalt_side", 18, -22, yaw: 90, scale: 1),   // far kerb, north end
    ]
    static let buildings: [WorldSite.Piece] = [
        .init("shed_wall", 24, -12, yaw: 90, scale: 1),   // THE LOW UNIT across the side street: five 3 m cubes in a row, x 22.5..25.5, z -13.5..1.5, 3 m tall flat-topped, 3 m behind the far footpath; 14.25 m from the plinth. This is its blank north end.
        .init("shed_wall", 24, -9, yaw: 90, scale: 1),   // low unit
        .init("shed_wall_garage", 24, -6, yaw: 90, scale: 1),   // low unit roller door: the garage face is on the cube's local -z, yaw 90 turns it to -x, onto the road
        .init("shed_wall", 24, -3, yaw: 90, scale: 1),   // low unit
        .init("shed_wall_window", 24, 0, yaw: 90, scale: 1),   // low unit office window at the south end, facing the road; on screen the unit's roofline rises out of the bottom-right corner (v about -8 at u 15, -5.7 at the right edge) and never touches the room
        .init("shed_wall_garage", -7.5, 21.5, yaw: -90, scale: 1),   // UNIT A across the front street: a 6 x 9 m joinery, cubes x -12..-6, z 20..29, face 1.5 m behind the far footpath, 12.75 m from the plinth. Roller doors on the +x face (yaw -90) so the camera sees them; this is the first.
        .init("shed_wall_garage", -7.5, 24.5, yaw: -90, scale: 1),   // Unit A second roller door, +x face
        .init("shed_wall_door", -7.5, 27.5, yaw: -90, scale: 1),   // Unit A personnel door at the back of the +x face
        .init("shed_wall_window", -10.5, 21.5, yaw: 0, scale: 1),   // Unit A office window on the street face (z 20), seen only when orbiting
        .init("shed_wall", -10.5, 24.5, yaw: 0, scale: 1),   // Unit A
        .init("shed_wall", -10.5, 27.5, yaw: 0, scale: 1),   // Unit A back corner. Unit A is off-frame at zoom 1 (its near corner is at u -18.4); it fills the bottom-left at zoom 0.8 and at the left orbit limit.
        .init("facade_metal", -18.5, 7, yaw: 180, scale: 1),   // THE WING'S SOUTH FACE, new: four corrugated tiles at z 7 facing +z (the street), x -29..-17, closing the wing's end 2.5 m behind the footpath; the compound's return fence meets its SE corner at (-17,7). The wing itself (x -17, z -17..7, 9 tiles, parapet, roof, HELLO FRIEND, eave flood) and the WAREHOUSE (z -17, two rows, lit bay at x 3 in line with the door) are KEPT in WorldYard with the edits listed in notes (the warehouse is cut back to end on the boundary at x 10.5).
        .init("facade_metal", -21.5, 7, yaw: 180, scale: 1),   // wing south face
        .init("facade_metal", -24.5, 7, yaw: 180, scale: 1),   // wing south face
        .init("facade_metal", -27.5, 7, yaw: 180, scale: 1),   // wing south face, west end under the roof box's edge (x -29.1)
    ]
    static let props: [WorldSite.Piece] = [
        .init("street_light", -15, 17.6, yaw: 0, scale: 1),   // FRONT STREET COLUMNS (light-curved @9, 6 m): four on the far footpath at 12 m spacing, arm over the road toward -z. The model is recentred: the shaft stands at z origin+0.77 = 18.37 (on the pavement z 17-18.5), the head hangs at about (x, 5.85, 16.7). This one is unlit (off-frame at zoom 1).
        .init("street_light", -3, 17.6, yaw: 0, scale: 1),   // LIGHT SOURCE sodium: column opposite the den; head at u -14, v -0.8, 4.8 m left of the room's SW corner on screen
        .init("street_light", 9, 17.6, yaw: 0, scale: 1),   // LIGHT SOURCE sodium: column near the T; its head pokes up from the bottom edge at u -5.5, v -5.7, 2.7 screen-m under the floor's front-left edge
        .init("street_light", 21, 17.6, yaw: 0, scale: 1),   // unlit column east of the T, below the frame
        .init("street_light", 17.6, -6, yaw: 90, scale: 1),   // SIDE STREET COLUMNS: yaw 90 puts the arm over the road toward -x and the shaft at x 18.37 (far pavement x 18-19.5); head at about (16.7, 5.85, z). LIGHT SOURCE sodium; head at u 16.1, v 0.5: right edge of the frame, beside the room, lights the road at the lot gate
        .init("street_light", 17.6, 6, yaw: 90, scale: 1),   // LIGHT SOURCE sodium; head at u 7.6, v -4.5, 2.4 screen-m under the floor's right edge, its pool on the bottom-right road
        .init("elec_pole_single", -18, 19.3, yaw: 0, scale: 1),   // POLE LINE along the back of the far footpath, 10 m spacing, crossarm across the line (local z) so the wires run along x. CONVERT as elec_pole_single: roads/electricity-pole-single.glb --join --recenter --scale 10 --color colormap=0.30,0.24,0.18 (scale 10, not the script's default 8, to match elec_pole and the wire height). Wires: elec_wires_wide (see notes) at y 4.2 between poles, placed from WorldYard because the site tables cannot lift a prop.
        .init("elec_pole_single", -8, 19.3, yaw: 0, scale: 1),   // pole in front of Unit A's east corner; in frame at the left edge (u -17.2, top v -3.3)
        .init("elec_pole_single", 2, 19.3, yaw: 0, scale: 1),   // pole behind the bus stop; pokes 3.8 m up from the bottom edge at u -12.2
        .init("elec_pole_single", 12, 19.3, yaw: 0, scale: 1),   // pole; just below the frame at zoom 1
        .init("elec_pole_single", 22, 19.3, yaw: 0, scale: 1),   // pole, terminal; below the frame
        .init("bench", 1.5, 17.95, yaw: 0, scale: 1),   // BUS STOP: detail-bench @3 (1.82 x 1.23 x 0.96) on the far footpath, seat toward the road (flip to 180 if the backrest lands roadside); 10.7 m from the plinth, 1.23 m tall
        .init("road_sign_empty", 2.8, 18.2, yaw: 0, scale: 1),   // BUS STOP FLAG: blank plate on a pole. CONVERT as road_sign_empty: roads/road-sign-empty.glb --join --recenter --scale 6 --color colormap=0.30,0.31,0.32 (2.9 m like the other signs; the script would propose 8). 10.95 m from the plinth.
        .init("sign_street", 20.2, 10.3, yaw: 0, scale: 1),   // street-name blades on the far corner of the T (near-kerb pavement of the tile at x 21), 2.85 m, 11.3 m from the plinth corner; below the frame at zoom 1, seen at 0.8 and the left orbit limit
        .init("primitive:hydrant", 19, 10.4, yaw: 0, scale: 1),   // hydrant on the far corner's pavement quarter-disc (1.0 m from its centre (19.5,9.5)); the builder draws it red, the site's one small colour accent apart from the cones; 11.2 m from the plinth, 0.85 m tall
        .init("primitive:drain", 3.6, 11.25, yaw: 0, scale: 1),   // gutter grate on the front street's asphalt against the near kerb face (z 11); the moved cone stands beside it
        .init("primitive:drain", 12.35, 5.2, yaw: 0, scale: 1),   // gutter grate against the side street's near kerb (x 12), the low point by the den's corner
        .init("primitive:manhole", 1.5, 14, yaw: 0, scale: 1),   // manhole in the front street's centre tile
        .init("primitive:manhole", 15, -2, yaw: 0, scale: 1),   // manhole in the side street's centre tile
        .init("primitive:bollard", -13.9, 10.2, yaw: 0, scale: 1),   // bollard guarding the compound gate post, on the raised pavement just west of the crossover (x < -13.5)
        .init("primitive:bollard", -8.1, 10.2, yaw: 0, scale: 1),   // bollard east of the compound crossover (x > -7.5), 2.9 m from the plinth's SW corner
        .init("barrier_concrete", 5, 19.4, yaw: 0, scale: 1),   // jersey barrier (2 m, x 4..6) blocking the vacant lot's old crossover, 0.9 m behind the far footpath
        .init("barrier_concrete", 7.2, 19.4, yaw: 0, scale: 1),   // second barrier x 6.2..8.2
        .init("billboard", 7.5, 22, yaw: 90, scale: 1),   // HOARDING on the vacant lot: sign-highway @7, 7 m wide x 4.95 m; yaw 90 lays the board along x (x 4..11) facing the road, so the camera sees its braced back. Greyed blank. 14.75 m from the plinth; its top 2 m show across the bottom-left of the frame (u -12.7..-7.8, v -8).
        .init("tree_shrub", 2, 21.8, yaw: 0, scale: 1),   // weeds on the vacant lot (2.3 m wide, 0.9 m tall)
        .init("tree_shrub", 9.5, 21.2, yaw: 40, scale: 1),   // weeds
        .init("tree_shrub", 5.5, 26.5, yaw: 110, scale: 1),   // weeds
        .init("tree_shrub", 12.5, 24, yaw: 70, scale: 1),   // weeds
        .init("primitive:tyres", 10.8, 27, yaw: 20, scale: 1),   // dumped tyres in the weeds
        .init("trash_bags", 3.4, 24.6, yaw: 110, scale: 1),   // fly-tipped bags on the vacant lot
        .init("pallet_broken", 7, 25.8, yaw: 35, scale: 1),   // dumped broken pallet
        .init("tree_shrub", -7.6, 9.9, yaw: 0, scale: 0.2),   // weeds (1.4 m wide, 0.54 m tall) through the compound's short fence panel onto the footpath, 3.1 m from the plinth's SW corner
        .init("tree_shrub", -16.6, 9.9, yaw: 30, scale: 0.2),   // weeds at the wing's corner post
        .init("tree_shrub", 10.3, -5, yaw: 70, scale: 0.2),   // weeds at the lot's east return corner, 2.05 m from the plinth's east edge and level with the back wall
        .init("city_dumpster", 21.3, -9.6, yaw: 90, scale: 1),   // the low unit's bin on its apron beside the roller door (x 20.4..22.2), 1.05 m tall, 13 m from the plinth
        .init("truck_flat", 21.6, 7.5, yaw: 0, scale: 1),   // a flatbed parked nose-north on the neighbour's hardstand south of the low unit (x 20.35..22.85, z 5..10); 12.1 m from the plinth; only its cab roof pokes 1.2 m up at the bottom right (u 11). The one vehicle in the foreground half.
        .init("unit_k", 15, -34, yaw: 0, scale: 1),   // listed under distant as well; see there
    ]
    static let distant: [WorldSite.Piece] = [
        .init("unit_k", 15, -34, yaw: 0, scale: 1),
        .init("lowdetail_wide_b", -36, 14, yaw: 90, scale: 1),
    ]
    static let areas: [WorldSite.Area] = [
        .init("asphalt hardstand: the neighbour's yard east of the side street, x 19.5..32, z -25..10 (starts at the far footpath's back edge, 15 cm below the pavement top); the low unit, its dumpster and the flatbed stand on it", 25.75, -7.5, 12.5, 35),
        .init("concrete forecourt: Unit A's ground across the front street, x -15..0, z 18.5..30 (its +x side is the forecourt the roller doors open onto; reached by the crossover at x -3)", -7.5, 24.25, 15, 11.5),
        .init("dirt (vacant ground): the empty block across the front street, x 0..15, z 18.5..30, with weeds, dumped tyres, bags and a broken pallet, the hoarding on it and the barriers across its old crossover", 7.5, 24.25, 15, 11.5),
    ]
    static let fence: [WorldSite.Fence] = [
        .init("chainlink", -15.25, 9.5, yaw: 0, length: 3.5),
        .init("gate", -11, 9.5, yaw: 0, length: 5),
        .init("chainlink", -7.5, 9.5, yaw: 0, length: 2),
        .init("chainlink", -6.5, 8.25, yaw: 90, length: 2.5),
        .init("chainlink", -17, 8.25, yaw: 90, length: 2.5),
        .init("chainlink", 10.5, -15.75, yaw: 90, length: 2.5),
        .init("gate", 10.5, -11.5, yaw: 90, length: 6),
        .init("chainlink", 10.5, -7.05, yaw: 90, length: 2.9),
        .init("chainlink", 9.375, -5.6, yaw: 0, length: 2.25),
    ]
    static let lights: [WorldSite.Light] = [
        .init("sodium point (street column head)", -3, 5.85, 16.7, color: "#ffb86b", lumens: 120000),   // front street column opposite the den (prop at (-3,17.6)); builder radius max(10,4y)=23 m; daylight.addStreetLight; lights the road, the bus stop and the den's near kerb
        .init("sodium point (street column head)", 9, 5.85, 16.7, color: "#ffb86b", lumens: 120000),   // front street column by the T (prop at (9,17.6)); its pool is mostly below the frame, the kerb in front of the den catches its edge
        .init("sodium point (street column head)", 16.7, 5.85, -6, color: "#ffb86b", lumens: 120000),   // side street column at the lot gate (prop at (17.6,-6)); right edge of the frame
        .init("sodium point (street column head)", 16.7, 5.85, 6, color: "#ffb86b", lumens: 120000),   // side street column beside the den's east apron (prop at (17.6,6)); the pool on the bottom-right road. EXISTING lights stay in WorldYard: cold LED at both windows (-8.4,2.6,+-2.2), warm LED at the door (5.2,2.6,-8.2), sodium posts A (-12.7,4.55,-12.9), B moved to (-11.9,4.55,6.7), the lot post moved to (8.65,4.55,-7.2), floods at the bay and the wing eave, the lit bay, the amber beacon. Outdoor total 14 (10 today).
    ]
}
