#!/usr/bin/env python3
"""Turn a site plan (the JSON the design workflow produces) into Swift tables.

    python3 Assets/site_to_swift.py Assets/work/site-plan.json

Writes Sources/amux/World/WorldSiteData.swift and prints the pieces the plan
uses that are not converted yet, with the manifest lines to add for them
(kit file names are resolved through build_assets.py's MANIFEST).
"""
import json, re, sys, os

HERE = os.path.dirname(os.path.abspath(__file__))
plan = json.load(open(sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "work/site-plan.json")))
if "final" in plan:
    plan = plan["final"]

# name -> kit path from the manifest, and the reverse for kit files
manifest = {}
for m in re.finditer(r'["\']([a-z0-9_]+)["\']:\s*\(\s*["\']([^"\']+)["\']', open(os.path.join(HERE, "build_assets.py")).read()):
    manifest[m.group(1)] = m.group(2)
# the scale each piece was converted at, so a plan's kit-unit scale can be divided out
conv_scale = {}
for m in re.finditer(r'["\']([a-z0-9_]+)["\']:\s*\([^)]*?["\']--scale["\'],\s*["\']([0-9.]+)["\']', open(os.path.join(HERE, "build_assets.py")).read()):
    conv_scale[m.group(1)] = float(m.group(2))
by_file = {}
for name, path in manifest.items():
    base = os.path.basename(path)
    by_file.setdefault(base[:-4] if base.endswith(".glb") else base, name)
    by_file.setdefault(base, name)

converted = {f[:-5] for f in os.listdir(os.path.join(HERE, "../Sources/amux/Resources/world")) if f.endswith(".usdz")}

KITS = {  # default scale per kit for pieces that still need converting
    "kenney-city-kit-roads": 8, "kenney-retro-urban-kit": 3, "kenney-city-kit-commercial": 7,
    "kenney-modular-buildings": 5, "kenney-building-kit": 1, "quaternius-cyberpunk-game-kit": 1,
    "polypizza-hacker-props": 1, "poly-pizza-workstations": 1,
}
inventory = json.load(open(os.path.join(HERE, "work/kit-inventory.json")))
kit_dirs = {"roads": "kenney-city-kit-roads/Models/GLB format", "commercial": "kenney-city-kit-commercial/Models/GLB format",
            "modular": "kenney-modular-buildings/Models/GLB format", "retro-urban": "kenney-retro-urban-kit/Models/GLB format",
            "building-kit": "kenney-building-kit/Models/GLB format", "cyberpunk": "quaternius-cyberpunk-game-kit",
            "hacker-props": "polypizza-hacker-props"}
file_to_kit = {}
for kit, items in inventory.items():
    if kit == "converted_world_assets":
        continue
    for it in items:
        file_to_kit.setdefault(it["file"][:-4], kit)

missing = {}

NAMED = {"weeds": "tree_shrub", "weed": "tree_shrub", "trashcan_kenney": "trashcan", "trash_can": "trashcan", "bin": "trashcan",
         "electricity_pole_single": "elec_pole_single", "electricity_wires_wide": "elec_wires_wide", "electricity_pole_wide": "electricity_pole_wide"}
ALIASES = [("road_sign_", "sign_"), ("road_asphalt_", "asphalt_"), ("detail_", ""), ("electricity_", "elec_"),
           ("elec_pole", "elec_pole_city"), ("elec_wires", "elec_wires_city"), ("light_curved", "street_light"), ("tree_", "tree_")]

def resolve(piece):
    """A converted asset name for a plan piece, or a proposed one. Free-text
    descriptions (spaces, slashes) are not pieces and come back as None."""
    p = re.sub(r"\(.*?\)", "", piece).strip()
    if " " in p or "/" in p or not p:
        return None
    if p in converted:
        return p
    if p.endswith(".glb"):
        p = p[:-4]
    if p in by_file and by_file[p] in converted:
        return by_file[p]
    snake = re.sub(r"[^a-z0-9]+", "_", p.lower()).strip("_")
    if p.startswith("primitive:"):
        return p                                   # WorldSite draws these itself
    if p.startswith("graffiti:"):
        return None                                # the tags are already in the yard
    if snake in NAMED and NAMED[snake] in converted:
        return NAMED[snake]
    if snake in converted:
        return snake
    for old, new in ALIASES:
        if snake.startswith(old):
            cand = new + snake[len(old):]
            if cand in converted:
                return cand
            if cand.rstrip("_") in converted:
                return cand.rstrip("_")
    # propose a conversion
    kit = file_to_kit.get(p)
    if kit:
        d = kit_dirs[kit]
        scale = KITS[d.split("/")[0]]
        missing[snake] = f'    "{snake}": ("{d}/{p}.glb", ["--scale", "{scale}", "--recenter"]),'
    else:
        missing[snake] = f"    # UNKNOWN PIECE {piece!r}"
    return snake

def f(v):
    return f"{float(v):g}"

out = []
out.append("// Generated by Assets/site_to_swift.py from Assets/work/site-plan.json. Do not edit by hand.\n")
out.append("import Foundation\n")
out.append("enum WorldSiteData {")
out.append(f"    static let gridUnit: Float = {f(plan.get('grid_unit', 8))}")
out.append(f"    static let groundColor = {json.dumps(plan['ground'].get('base_color', 'concrete'))}")

def pieces(key, items):
    out.append(f"    static let {key}: [WorldSite.Piece] = [")
    for it in items:
        name = resolve(it["piece"])
        note = (it.get("note") or "").replace("\n", " ")
        if name is None:
            out.append(f"        // (description, not a piece: {it['piece']!r})")
            continue
        # plans quote scale in kit units; the converted piece already carries its kit scale
        want = float(it.get('scale', 1) or 1)
        eff = 1.0 if want == 1 else max(0.2, want / conv_scale.get(name, 1.0))
        out.append(f"        .init(\"{name}\", {f(it['x'])}, {f(it['z'])}, yaw: {f(it.get('yaw', 0))}, scale: {f(eff)}),"
                   + (f"   // {note}" if note else ""))
    out.append("    ]")

pieces("roads", plan.get("roads", []))
pieces("buildings", plan.get("buildings", []))
pieces("props", plan.get("props", []))
pieces("distant", plan.get("distant", []))

out.append("    static let areas: [WorldSite.Area] = [")
for a in plan["ground"].get("areas", []):
    out.append(f"        .init({json.dumps(a['kind'])}, {f(a['x'])}, {f(a['z'])}, {f(a['w'])}, {f(a['d'])}),")
out.append("    ]")

out.append("    static let fence: [WorldSite.Fence] = [")
for s in plan.get("fence", []):
    out.append(f"        .init({json.dumps(s['kind'])}, {f(s['x'])}, {f(s['z'])}, yaw: {f(s['yaw'])}, length: {f(s['length'])}),")
out.append("    ]")

out.append("    static let lights: [WorldSite.Light] = [")
for l in plan.get("lights", []):
    note = (l.get("note") or "").replace("\n", " ")
    out.append(f"        .init({json.dumps(l['kind'])}, {f(l['x'])}, {f(l['y'])}, {f(l['z'])}, color: {json.dumps(l['color'])}, lumens: {f(l['lumens'])}),"
               + (f"   // {note}" if note else ""))
out.append("    ]")
out.append("}")

dst = os.path.join(HERE, "../Sources/amux/World/WorldSiteData.swift")
open(dst, "w").write("\n".join(out) + "\n")
print(f"wrote {os.path.relpath(dst, HERE)}: {len(plan.get('roads', []))} roads, {len(plan.get('buildings', []))} buildings, "
      f"{len(plan.get('props', []))} props, {len(plan.get('distant', []))} distant, {len(plan.get('fence', []))} fence, {len(plan.get('lights', []))} lights")
if missing:
    print(f"{len(missing)} pieces need converting; add to MANIFEST:")
    for line in missing.values():
        print(line)
    open(os.path.join(HERE, "work/site-missing.txt"), "w").write("\n".join(missing.values()) + "\n")
    open(os.path.join(HERE, "work/site-missing-names.txt"), "w").write(" ".join(k for k, v in missing.items() if not v.strip().startswith("#")))
else:
    for p in ("work/site-missing.txt", "work/site-missing-names.txt"):
        try: os.remove(os.path.join(HERE, p))
        except FileNotFoundError: pass
